print("Hello World!")
print("Hello again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("I am happy that tommorow is a weekend!")
print('I "said" do not touch this.')